version: "3.7"

services:
  client:
    build: .
    image: react-app
    container_name: react-container
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - app
    command: npm run client
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: ts-container
    volumes:
      - .:/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: "practice"
      DB_PASSWORD: "practice"
      DB_NAME: "practice"
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 100
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 10
    command: "npm run dev"
    networks:
      - app

networks:
  app:
    driver: bridge
