version: "3.7"

services:
  client:
    build: .
    image: react-app
    container_name: react-container
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - app
    command: npm run client
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: ts-container
    volumes:
      - .:/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run dev"
    networks:
      - app

networks:
  app:
    driver: bridge
